"""set single parent

Revision ID: 15ac40aa23f5
Revises: a04c213a6c1c
Create Date: 2022-11-18 14:15:40.946905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "15ac40aa23f5"
down_revision = "a04c213a6c1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
