"""set cascade options

Revision ID: a04c213a6c1c
Revises: bc8b32e8e22d
Create Date: 2022-11-18 14:13:48.197649

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "a04c213a6c1c"
down_revision = "bc8b32e8e22d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
