"""init basic migrations

Revision ID: bc8b32e8e22d
Revises:
Create Date: 2022-11-18 13:57:01.655972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "bc8b32e8e22d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pronoun",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subj", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obj", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("posDet", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("posPro", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refl", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pronoun")
    op.drop_table("user")
    # ### end Alembic commands ###
