"""set user_id as optional

Revision ID: fef088232db6
Revises: 3b1a61fe421d
Create Date: 2022-11-18 17:21:02.439040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fef088232db6'
down_revision = '3b1a61fe421d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
